# Generated by Django 3.0.5 on 2020-05-19 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaCerveza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('sitioweb', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='TipoCerveza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='NombreCerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TipoCerveza')),
            ],
            options={
                'verbose_name': 'cerveza',
                'verbose_name_plural': 'cervezas',
                'ordering': ['tipo'],
            },
        ),
    ]
