# Generated by Django 3.0.6 on 2020-05-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaCerveza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(default='S/M', max_length=50)),
                ('sitioweb', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='TipoCerveza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='None', max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='NombreCerveza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=600)),
                ('precio', models.CharField(max_length=4, null=True)),
                ('foto', models.ImageField(null=True, upload_to='fotocerv')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MarcaCerveza')),
                ('tipo', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='polls.TipoCerveza')),
            ],
            options={
                'verbose_name': 'Cerveza',
                'verbose_name_plural': 'Cervezas',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='marcacerveza',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Origen'),
        ),
    ]
