# Generated by Django 3.0.5 on 2020-05-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacerveza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocerveza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
