# Generated by Django 3.0.5 on 2020-05-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200518_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombrecerveza',
            name='marca',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.MarcaCerveza'),
        ),
    ]
